DROP DATABASE CRAWLER;
CREATE DATABASE CRAWLER;
USE CRAWLER;

CREATE TABLE POSTS (
    ID INT(255) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    POST_ID INT(255) NOT NULL UNIQUE,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(40) NOT NULL,
    DATE VARCHAR(40) NOT NULL,
    CONTENT_HTML TEXT NOT NULL,
    URL TEXT NOT NULL,
    FORUM_ID INT(255) NOT NULL,
    TOPIC_ID INT(255) NOT NULL
);

ALTER TABLE POSTS CONVERT TO CHARACTER SET utf8;

CREATE TABLE TOPICS (
    ID INT(255) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TOPIC_ID INT(255) NOT NULL UNIQUE,
    FORUM_ID INT(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT_HTML TEXT NOT NULL,
    URL TEXT NOT NULL
);

ALTER TABLE TOPICS CONVERT TO CHARACTER SET UTF8;

CREATE TABLE FORUMS (
    ID INT(255) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FORUM_ID INT(255) NOT NULL UNIQUE,
    TITLE VARCHAR(255) NOT NULL,
    URL TEXT NOT NULL
);

ALTER TABLE FORUMS CONVERT TO CHARACTER SET UTF8;
